import org.gradle.internal.resource.transport.http.HttpClientHelper
import java.net.Authenticator
import java.net.PasswordAuthentication

allprojects {
    buildscript {
        repositories.all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                repo.allowInsecureProtocol = true
            }
        }
    }
    repositories.all { ArtifactRepository repo ->
        if (repo instanceof MavenArtifactRepository) {
            repo.allowInsecureProtocol = true
        }
    }
}

gradle.projectsLoaded {
    // Set default authenticator
    Authenticator.setDefault(new Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(
                "container_container_01LuUyT6GnHkJeshkrAPkXG8--claude_code_remote--flaky-sugary-free-gleam",
                "jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjRiNTc2Yjk3LWY0NDctNGRlZS04NTQwLWUzYzFlNTA5NjMyMyIsImlhdCI6MTc2MzIyMTAyNywiZXhwIjoxNzYzMjM1NDI3LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwic2Vzc2lvbl9pZCI6InNlc3Npb25fMDFCOFhXS1lYQmZvdFN4alJOWTN6ZXZiIiwiY29udGFpbmVyX2lkIjoiY29udGFpbmVyXzAxTHVVeVQ2R25Ia0plc2hrckFQa1hHOC0tY2xhdWRlX2NvZGVfcmVtb3RlLS1mbGFreS1zdWdhcnktZnJlZS1nbGVhbSJ9.XD7WFkIBpaWp3OK8gNwU7aZkN1dR4mdpubICcIXmGnqaiLh-iUnd3_j9Mzbj-irGLLSl1-Y4-6C9FqUBtv55eg".toCharArray()
            )
        }
    })
}
