import org.gradle.internal.resource.transport.http.HttpClientHelper
import java.net.Authenticator
import java.net.PasswordAuthentication

allprojects {
    buildscript {
        repositories.all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                repo.allowInsecureProtocol = true
            }
        }
    }
    repositories.all { ArtifactRepository repo ->
        if (repo instanceof MavenArtifactRepository) {
            repo.allowInsecureProtocol = true
        }
    }
}

gradle.projectsLoaded {
    // Set default authenticator
    Authenticator.setDefault(new Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(
                "container_container_01XPWq2XiuUzi2Sy7fJkXU1p--claude_code_remote--fast-best-dry-junk",
                "jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjRiNTc2Yjk3LWY0NDctNGRlZS04NTQwLWUzYzFlNTA5NjMyMyIsImlhdCI6MTc2MzUxMzYwOSwiZXhwIjoxNzYzNTI4MDA5LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwic2Vzc2lvbl9pZCI6InNlc3Npb25fMDE0MTF1UUU5ZVcxV2kxYTdjaDJGeWY1IiwiY29udGFpbmVyX2lkIjoiY29udGFpbmVyXzAxWFBXcTJYaXVVemkyU3k3ZkprWFUxcC0tY2xhdWRlX2NvZGVfcmVtb3RlLS1mYXN0LWJlc3QtZHJ5LWp1bmsifQ.cLxfqx9Lezdin663oy1DwPk--wpxx581O8UuvWxn3qjsUjPAmSUROY4xePaIUHmKXTdXnbINnjGrtJJ7A_0E6A".toCharArray()
            )
        }
    })
}
